modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="wasteddeath"
version="1.2"
displayName="Wasted Death"
authors="Redstoneguy129"
description="Wasted screen from GTA on death."

[[dependencies.wasteddeath]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wasteddeath]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
